Mostly working...

diff --git a/gclone b/gclone
--- a/gclone
+++ b/gclone
@@ -1,9 +1,18 @@
 #!/bin/sh
+
 if [ "$#" != 1 ] || [ "$1" == "--help" ]; then
 	echo "gclone -- clone a repo into the current directory."
 	echo "usage: gclone [address]" 
 	echo "e.g. gclone https://github.com/terriblememory/stupidgit.git"
 	exit
 fi
+
 ADDRESS=$1
-git clone $ADDRESS .
+
+echo "Cloning from '$ADDRESS'."
+if !(git clone $ADDRESS .); then
+    echo "ERROR: 'git clone' failed."
+    exit 1
+fi
+
+echo "Done."
diff --git a/ginit b/ginit
--- a/ginit
+++ b/ginit
@@ -1,43 +1,56 @@
 #!/bin/sh
 
 if [ "$#" != 1 ] || [ "$1" == "--help" ]; then
-	echo "ginit -- create a local repo and set its origin."
-	echo "usage: ginit [address]" 
-	echo "e.g. ginit https://github.com/terriblememory/stupidgit.git"
+	echo "  ginit -- create  local repo in current directory and set origin remote."
+	echo "  usage: ginit [address]" 
+	echo "  e.g. ginit https://github.com/terriblememory/stupidgit.git"
     exit 1
 fi
 
 ADDRESS=$1
 
-# TODO: Verify that this isn't already an initialized repo.
-
-if (git rev-parse); then
-    echo "This is already a git repository. Maybe you meant gpull/gpush?"
+if (git rev-parse 2>/dev/null); then
+    echo "ERROR: Already a git repository. This script is too dumb to handle that!"
     exit 1
-    # TODO: Maybe check that the origin has been set up and help with that if not?
+fi
+
+echo "Ensuring remote '$ADDRESS' is empty..."
+if (git ls-remote --exit-code $ADDRESS); then
+    echo "ERROR: Remote '$ADDRESS' is NOT empty."
+    exit 1
 fi
 
 if !(git init); then
-    echo "'git init' failed."
+    echo "ERROR: 'git init' failed."
     exit 1
 fi
 
 if !(git add .); then
-    echo "'git add' failed."
+    echo "ERROR: 'git add' failed."
     exit 1
 fi
 
+if [ -z "$(git status --porcelain)" ]; then
+    echo "ERROR: Nothing to commit. Do some work then try again! Removing empty repo."
+    rm -rf .git
+    exit 1
+fi
+
+echo "Performing initial commit to the local repo."
 if !(git commit -m "Initial commit."); then
-    echo "'git commit' failed."
+    echo "ERROR: 'git commit' failed."
     exit 1
 fi
 
 if !(git remote add origin $ADDRESS); then
-    echo "'git remote' failed."
+    echo "ERROR: 'git remote' failed."
     exit 1
 fi
 
+echo "Performing initial push to the remote origin."
 if !(git push -u origin master); then
-    echo "'git push' failed."
+    echo "ERROR: 'git push' failed."
     exit 1
 fi
+
+echo "Done."
diff --git a/gspull b/gspull
--- a/gspull
+++ b/gspull
@@ -1,10 +1,19 @@
 #!/bin/sh
-if [ "$#" == 0 ]; then
-	echo "gspull -- pull subtree updates from subtree origin."
-	echo "usage: gspull subname" 
-	echo "e.g. gspull stupidgit"
-	exit
-fi
-SUBNAME=$1
-git subtree pull --prefix=$SUBNAME --squash $SUBNAME master
 
+if [ "$#" != 1 ] || [ "$1" == "--help" ]; then
+	echo "  gspull -- update a subtree from its remote origin."
+	echo "  usage: gspull [subdir]" 
+    echo "  Run this script from the root directory of the containing repository."
+    echo "  [subdir] is the relative subdirectory of the subtree."
+	echo "  e.g. gspull mylib"
+	exit 1
+fi
+
+SUBDIR=$1
+
+if !(git subtree pull --prefix=$SUBDIR --squash $SUBDIR master); then
+    echo "ERROR: Unable to pull subtree."
+    exit 1
+fi
+
+echo "Done."
diff --git a/gspush b/gspush
--- a/gspush
+++ b/gspush
@@ -1,9 +1,17 @@
 #!/bin/sh
+
 if [ "$#" == 0 ]; then
-	echo "gspush -- push subtree changes to subtree origin."
-	echo "usage: gspush subname" 
-	echo "e.g. gspush stupidgit"
+	echo "  gspush -- push subtree changes to subtree origin."
+	echo "  usage: gspush subname" 
+	echo "  e.g. gspush stupidgit"
 	exit
 fi
+
 SUBNAME=$1
-git subtree push --prefix=$SUBNAME --squash $SUBNAME master
+
+if !(git subtree push --prefix=$SUBNAME --squash $SUBNAME master); then
+    echo "ERROR: Unable to pull subtree."
+    exit 1
+fi
+
+echo "Done."
