Tweaks...

diff --git a/gpull b/gpull
--- a/gpull
+++ b/gpull
@@ -1,8 +1,12 @@
 #!/bin/sh
-if [ "$1" == "--help" ]; then
-	echo "gpull -- pull repo changes from origin."
+
+if [ "$#" != 0 ]; then
+	echo "gpull -- pull repo changes from origin"
 	echo "usage: gpull" 
-	echo "e.g. gpull"
-	exit
+	exit 1
 fi
-git pull
+
+if !(git pull origin master); then
+    echo "'git pull' failed."
+    exit 1
+fi
diff --git a/gpush b/gpush
--- a/gpush
+++ b/gpush
@@ -2,15 +2,9 @@
 
 if [ "$1" == "--help" ]; then
 	echo "gpush -- push repo changes to origin"
-	echo "usage: gpush {address}" 
-	echo "e.g. gpush https://github.com/terriblememory/stupidgit.git to establish"
-	echo "     the remote, and subsequenly just gpush (with no address) to push changes."
-	exit
+	echo "usage: gpush" 
+	exit 1
 fi
-
-# TODO: Verify that the local copy is up to date with the origin. If not the
-# user should do a gpull and resolve any conflicts before trying gpush again.
-# (There's no need to do this if the origin has been established yet.)
 
 if !(git add .); then
     echo "'git add' failed."
@@ -23,6 +17,6 @@ if !(git commit); then
 fi
 
 if !(git push origin master); then
-    echo "'git push' failed."
-    exit 1
+	echo "'git push' failed" 
+	exit 1
 fi
